### ISSUE TITLE
Taxonium -adding additional tracks option

### ISSUE THREAD

**Issue by ucscbrianlee** [pathogen-genomics/introduction-website#16]
In Russ's March 10th TOAST (Technical Outreach and Assistance for States Team) talk he shared that Treenome within Taxonium can view tracks such as the Bloom lab’s mutation mapping scores.

It appears these tracks (all tracks besides sequence) are missing in the CDPH Big Tree Taxonium view. 

This ticket is to follow whether it is possible to add those tracks, with users most interested in the Bloom lab’s mutation mapping scores.  Related [user-email issue](https://github.com/pathogen-genomics/user-email/issues/14).

**Comment by amkram** [comment]
Hi @ucscbrianlee , I'm not super familiar with how the CDPH view is set up - But, I think it should be possible to get those tracks loaded in the Big Tree view. Before we serve the UCSC SARS-CoV-2 annotations, we check if the URL is "cov2tree.org," which is the main Taxonium build of the public tree (to avoid loading CoV-2 annotations on other trees). So, if you are able to share the URL of the Big Tree view (maybe via DM if not public?) or at least the domain name, I should be able to add that in.

**Comment by ucscbrianlee** [comment]
Hi Alex,  that might be part of the mechanics.  The CDPH view is behind a password view, so maybe that has elements involved.  I'll let Jen @jen-martin or Koorous @kvargha share more details, perhaps in DM). It could be this was already discussed once, and I just didn't know about these details.

**Comment by kvargha** [comment]
@amkram Do you need the URL of the backend server or the URL of the tree file?

**Comment by amkram** [comment]
@kvargha I think either should be fine. The way this currently works is that I check to see if the current window's URL contains the substring "cov2tree" to decide if the app is looking at a SARS-CoV-2 tree or not. If you can provide a unique substring of the URL that is displayed while someone is using the Big Tree app, I can check for the presence of that in the JS code.

**Comment by kvargha** [comment]
Thanks for the explanation, I'll dm you the backend link @amkram.

**Comment by amkram** [comment]
This should be fixed in https://github.com/theosanderson/taxonium/pull/473

**Comment by kvargha** [comment]
Thank you @amkram. It's working. 
@ucscbrianlee can you please look to see if it's working correctly?

**Comment by ucscbrianlee** [comment]
This is beautiful!  Thank you Koorous @kvargha and Alex @amkram !

I can see the tracks now. I decided to use it to look at the DS.1 variant, it is defined by two mutations of concern within the RBD domain. You can see in this image in Treenome where the S:F486S mutation looks to be the perhaps higher scoring Bloom variant, on the right side. 

![DS1_F486S](https://user-images.githubusercontent.com/104174066/225083664-5db46dd9-0bc8-4ffe-be08-31c31ca7f1ae.png)

Having the Treenome browser with all this data within the Taxonium display in with CDPH Big Tree cluster annotation is really cool!   

Thank you so much for the work adding this!

**Comment by ucscbrianlee** [comment]
I'm closing this issue, thanks again so much for all the work adding tracks to the Big Tree Taxonoium Treenome browser. I love turning on some of the tracks and thinking about what new data connections can be made exploring the phylogenetic tree around new curious variants that pop-up (EK,DT).
